/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Comp.Panel;

import org.apache.poi.ss.usermodel.*;
import BUS.ConnectDB;
import BUS.DetailImportBillBUS;
import BUS.ImportBillBUS;
import BUS.StaffBUS;
import BUS.SupplierBUS;
import DTO.DetailImportBillDTO;
import DTO.ImportBillDTO;
import DTO.SupplierDTO;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.io.FileOutputStream;
import Helper.Format;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import GUI.Comp.Dialog.DialogDetailImport;
import GUI.Comp.Dialog.DialogDetailsImportBill;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JLabel;

/**
 *
 * @author Tai
 */
public class QuanLiNhapKho extends javax.swing.JPanel {
    
    private ImportBillBUS importBillBUS = new ImportBillBUS();
    private ArrayList<ImportBillDTO> importBillList = new ArrayList<>();
    private DefaultTableModel model = new DefaultTableModel();
    private SupplierBUS supplierBUS = new SupplierBUS();
    private StaffBUS staffBUS = new StaffBUS();
    private int selectedRow = -1;
    
    public QuanLiNhapKho() {
        initComponents();
        loadImportBills();
        jTextField1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "dd/MM/YYYY");
        tbImportBill.setRowHeight(35);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tbImportBill.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.LEFT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        panelBackground6 = new GUI.Comp.Swing.PanelBackground();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        jPanel8 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        panelBackground8 = new GUI.Comp.Swing.PanelBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbImportBill = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        panelBackground1.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground1.setLayout(new java.awt.BorderLayout());

        panelBackground2.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground2.setMinimumSize(new java.awt.Dimension(20, 10));
        panelBackground2.setPreferredSize(new java.awt.Dimension(20, 10));
        panelBackground1.add(panelBackground2, java.awt.BorderLayout.LINE_START);

        panelBackground3.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground3.setPreferredSize(new java.awt.Dimension(10, 20));
        panelBackground1.add(panelBackground3, java.awt.BorderLayout.PAGE_START);

        panelBackground4.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground4.setMinimumSize(new java.awt.Dimension(20, 10));
        panelBackground4.setPreferredSize(new java.awt.Dimension(20, 10));
        panelBackground1.add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground5.setPreferredSize(new java.awt.Dimension(10, 20));
        panelBackground1.add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        panelBackground6.setBackground(new java.awt.Color(30, 30, 30));
        panelBackground6.setLayout(new java.awt.BorderLayout(0, 20));

        panelBackground7.setBackground(new java.awt.Color(35, 35, 35));
        panelBackground7.setPreferredSize(new java.awt.Dimension(100, 75));
        panelBackground7.setLayout(new javax.swing.BoxLayout(panelBackground7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setBackground(new java.awt.Color(35, 35, 35));
        jPanel8.setMaximumSize(new java.awt.Dimension(20, 23));
        panelBackground7.add(jPanel8);

        btnThem.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(84, 40));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        panelBackground7.add(btnThem);

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setMaximumSize(new java.awt.Dimension(20, 23));
        panelBackground7.add(jPanel2);

        btnChiTiet.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setMaximumSize(new java.awt.Dimension(84, 40));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        panelBackground7.add(btnChiTiet);

        jPanel11.setBackground(new java.awt.Color(35, 35, 35));
        jPanel11.setMaximumSize(new java.awt.Dimension(20, 23));
        panelBackground7.add(jPanel11);

        jButton6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton6.setText("Xuất Excel");
        jButton6.setMaximumSize(new java.awt.Dimension(84, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelBackground7.add(jButton6);

        jPanel9.setBackground(new java.awt.Color(35, 35, 35));
        jPanel9.setMaximumSize(new java.awt.Dimension(20, 23));
        panelBackground7.add(jPanel9);

        jButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton2.setText("Nhập  Excel");
        jButton2.setMaximumSize(new java.awt.Dimension(140, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(140, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelBackground7.add(jButton2);

        jPanel3.setBackground(new java.awt.Color(35, 35, 35));
        jPanel3.setMaximumSize(new java.awt.Dimension(20, 23));
        panelBackground7.add(jPanel3);

        jTextField1.setMaximumSize(new java.awt.Dimension(175, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(175, 40));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        panelBackground7.add(jTextField1);

        panelBackground6.add(panelBackground7, java.awt.BorderLayout.PAGE_START);

        panelBackground8.setBackground(new java.awt.Color(35, 35, 35));
        panelBackground8.setLayout(new java.awt.BorderLayout());

        tbImportBill.setBackground(new java.awt.Color(35, 35, 35));
        tbImportBill.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tbImportBill.setForeground(new java.awt.Color(255, 255, 255));
        tbImportBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn nhập", "Số loại nguyên liệu", "Tổng tiền", "Ngày nhập hàng", "Nhân viên nhập", "Nhà cung cấp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbImportBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbImportBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbImportBill);

        panelBackground8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBackground6.add(panelBackground8, java.awt.BorderLayout.CENTER);

        panelBackground1.add(panelBackground6, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelBackground1);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


 
    private void loadImportBills(){
        importBillList = importBillBUS.loadImportBills();
        model = (DefaultTableModel)tbImportBill.getModel();
        model.setRowCount(0);
        for (ImportBillDTO x : importBillList) {
            String nameSupplier = supplierBUS.getSupplierById(x.getSupplierID()).getName();
            String nameStaff =  staffBUS.getStaffById(x.getUserId()).getLast_name() + " " + staffBUS.getStaffById(x.getUserId()).getFirst_name();
            model.addRow(new Object[] {x.getId(), x.getQuantity(), Format.formatNumber.format(x.getTotal()), Format.formatDate.format(x.getImport_date()), nameStaff, nameSupplier});
        }
        model.fireTableDataChanged();
        tbImportBill.setModel(model);

    }


    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Lấy ngày được nhập vào từ text field
        String inputDate = jTextField1.getText().trim();

        // Khởi tạo TableRowSorter để lọc dữ liệu trong bảng jTable
        DefaultTableModel model = (DefaultTableModel) tbImportBill.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tbImportBill.setRowSorter(sorter);

        // Nếu ngày nhập vào có ít nhất 1 ký tự và đúng định dạng dd/MM/YYYY
        if (inputDate.length() > 0 && inputDate.matches("\\d{2}/\\d{2}/\\d{4}")) {
            // Tạo một RowFilter để lọc dữ liệu dựa trên ngày nhập vào
            RowFilter<DefaultTableModel, Object> filter = new RowFilter<DefaultTableModel, Object>() {
                @Override
                public boolean include(Entry<? extends DefaultTableModel, ? extends Object> entry) {
                    String dateInTable = entry.getStringValue(3); // Cột thứ 4 là cột import_date
                    return dateInTable.equals(inputDate);
                }
            };

            // Áp dụng RowFilter để lọc dữ liệu
            sorter.setRowFilter(filter);
        } else {
            // Nếu ngày nhập vào không hợp lệ, hiển thị toàn bộ dữ liệu trong bảng
            sorter.setRowFilter(null);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        // Thiết lập chỉ cho phép người dùng chọn file Excel
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "xls", "xlsx");
        fileChooser.setFileFilter(filter);

        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            // Xử lý file Excel được chọn ở đây
            // Ví dụ: Gọi một phương thức để xử lý dữ liệu từ file Excel
            processDataFromExcel(selectedFile);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    // Lấy ngày được nhập vào từ text field
    String inputDate = jTextField1.getText().trim();

    // Khởi tạo TableRowSorter để lọc dữ liệu trong bảng jTable
    DefaultTableModel model = (DefaultTableModel) tbImportBill.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tbImportBill.setRowSorter(sorter);

    // Nếu ngày nhập vào có ít nhất 1 ký tự và đúng định dạng dd/MM/YYYY
    if (inputDate.length() > 0 && inputDate.matches("\\d{2}/\\d{2}/\\d{4}")) {
        // Tạo một RowFilter để lọc dữ liệu dựa trên ngày nhập vào
        RowFilter<DefaultTableModel, Object> filter = new RowFilter<DefaultTableModel, Object>() {
            @Override
            public boolean include(Entry<? extends DefaultTableModel, ? extends Object> entry) {
                String dateInTable = (String) entry.getValue(3); // Cột thứ 4 là cột import_date
                return dateInTable.equals(inputDate);
            }
        };

        // Áp dụng RowFilter để lọc dữ liệu
        sorter.setRowFilter(filter);
    } else {
        // Nếu ngày nhập vào không hợp lệ, hiển thị toàn bộ dữ liệu trong bảng
        sorter.setRowFilter(null);
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // Tạo một JDialog mới
            JDialog dialog = new JDialog();

            // Thiết lập JPanel DialogDetailImport làm nội dung của JDialog
            DialogDetailImport dialogPanel = new DialogDetailImport();
            dialog.getContentPane().add(dialogPanel);

            // Thiết lập thuộc tính cho JDialog
            dialog.setSize(1120, 650); // Thiết lập kích thước
            dialog.setLocationRelativeTo(this); // Hiển thị JDialog ở giữa cửa sổ cha
            dialog.setModal(true); // Thiết lập JDialog là modal để chặn tương tác với các thành phần khác trong cửa sổ cha
            dialog.setVisible(true); // Hiển thị JDialog
            loadImportBills();
        } catch (Exception ex) {
            Logger.getLogger(QuanLiNhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            loadImportBills();
        } catch (Exception ex) {
            Logger.getLogger(QuanLiNhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
    
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn để xem chi tiết.");
            return;
        }
        DialogDetailsImportBill dialogDetailImport = new DialogDetailsImportBill(null, true);
        ImportBillDTO importBill = importBillList.get(selectedRow);

        dialogDetailImport.setImportBill(importBill);
        dialogDetailImport.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int selectedRow = tbImportBill.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn để xuất file Excel.");
            return;
        }

        try {
            // Tạo hộp thoại để người dùng chọn thư mục lưu file Excel
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            // Hiển thị hộp thoại và lấy kết quả từ người dùng
            int userSelection = fileChooser.showSaveDialog(this);

            // Nếu người dùng chọn một thư mục và nhấn OK
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                // Lấy thư mục được chọn bởi người dùng
                File selectedDirectory = fileChooser.getSelectedFile();

                // Tạo đường dẫn đầy đủ cho file Excel
                String filePath = selectedDirectory.getAbsolutePath() + "/ChiTietHoaDon_" + tbImportBill.getValueAt(selectedRow, 0) + ".xlsx";

                // Tạo workbook mới
                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("Chi tiết hóa đơn");

                // Code xuất file Excel
                // Tạo header cho thông tin chi tiết
                Row detailHeaderRow = sheet.createRow(0);
                String[] detailHeaders = {"ID hóa đơn", "ID chi tiết", "Số lượng", "Giá tiền mỗi kg/lít", "Tổng tiền", "ID nguyên liệu", "Tên nguyên liệu"};
                for (int i = 0; i < detailHeaders.length; i++) {
                    Cell cell = detailHeaderRow.createCell(i);
                    cell.setCellValue(detailHeaders[i]);
                }

                // Lấy thông tin chi tiết từ JTable
                long selectedBillId = (long) tbImportBill.getValueAt(selectedRow, 0);
                int rowIndex = 1;

                // Tạo một thể hiện của lớp DetailImportBillBUS
                DetailImportBillBUS detailImportBillBUS = new DetailImportBillBUS();

                // Gọi phương thức từ thể hiện đã tạo
                ArrayList<DetailImportBillDTO> detailImportBillList = detailImportBillBUS.getDetailImportBillByBillId(selectedBillId);
                SupplierDTO supplier = detailImportBillBUS.getSupplierById((long) tbImportBill.getValueAt(selectedRow, 5));

                for (DetailImportBillDTO detailImportBill : detailImportBillList) {
                    Row row = sheet.createRow(rowIndex++);
                    row.createCell(0).setCellValue(detailImportBill.getBillid()); // Bổ sung cột billid
                    row.createCell(1).setCellValue(detailImportBill.getId());
                    row.createCell(2).setCellValue(detailImportBill.getQuantity());
                    row.createCell(3).setCellValue(detailImportBill.getPrice());
                    row.createCell(4).setCellValue(detailImportBill.getTotal());
                    row.createCell(5).setCellValue(detailImportBill.getIngredientid());
                    long ingredientId = detailImportBill.getIngredientid();
                    //row.createCell(6).setCellValue(ingredientId); // Lưu ID nguyên liệu vào cột
                    // Lấy tên nguyên liệu từ bảng tb_ingredients
                    String ingredientName = detailImportBillBUS.getIngredientNameById(ingredientId);
                    if (ingredientName != null) {
                        row.createCell(6).setCellValue(ingredientName); // Lưu tên nguyên liệu vào cột
                    }
                }

                // Lấy thông tin nhà cung cấp từ BUS
                Row supplierHeaderRow = sheet.createRow(rowIndex++);
                supplierHeaderRow.createCell(0).setCellValue("Thông tin nhà cung cấp");
                rowIndex++;
                if (supplier != null) {
                    Row row = sheet.createRow(rowIndex++);
                    row.createCell(0).setCellValue("ID");
                    row.createCell(1).setCellValue(supplier.getId());
                    row = sheet.createRow(rowIndex++);
                    row.createCell(0).setCellValue("Tên");
                    row.createCell(1).setCellValue(supplier.getName());
                    row = sheet.createRow(rowIndex++);
                    row.createCell(0).setCellValue("Địa chỉ");
                    row.createCell(1).setCellValue(supplier.getAddress());
                    row = sheet.createRow(rowIndex++);
                    row.createCell(0).setCellValue("Số điện thoại");
                    row.createCell(1).setCellValue(supplier.getPhone());
                }

                // Lưu file Excel vào đường dẫn đã chọn
                FileOutputStream fileOut = new FileOutputStream(filePath);
                workbook.write(fileOut);
                fileOut.close();

                // Hiển thị thông báo khi xuất file Excel thành công
                JOptionPane.showMessageDialog(this, "Xuất file Excel thành công.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi xuất file Excel.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbImportBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbImportBillMouseClicked
        selectedRow = tbImportBill.getSelectedRow();
        
    }//GEN-LAST:event_tbImportBillMouseClicked

    private void processDataFromExcel(File file) {
        Connection con = null;
        try {
            con = ConnectDB.openConnect();

            Workbook workbook = WorkbookFactory.create(file);
            Sheet sheet = workbook.getSheetAt(0);

            int startRow = 2;
            int endRow = sheet.getLastRowNum();

            double total = 0;
            int quantity = 0;
            for (int i = startRow; i <= endRow; i++) {
                Row row = sheet.getRow(i);
                if (row != null) {
                    quantity++;
                    Cell totalCell = row.getCell(3);
                    if (totalCell != null) {
                        total += totalCell.getNumericCellValue();
                    }
                }
            }

//            // Get current date
//            java.util.Date currentDate = new java.util.Date();
//
//            
//            long userId = StaffDTO.staffLogging.getId();
//
//            String supplierIdInput = JOptionPane.showInputDialog(null, "Nhập supplierid:");
//            int supplierId = Integer.parseInt(supplierIdInput);
//
//            Cell billIdCell = sheet.getRow(2).getCell(4);
//            int billId = (int) billIdCell.getNumericCellValue();
//
//            ImportBillBUS importBillBUS = new ImportBillBUS();
//            importBillBUS.addImportBill(con, billId, quantity, total, new java.sql.Date(currentDate.getTime()), userId, supplierId);
//
//            for (int i = startRow; i <= endRow; i++) {
//                Row row = sheet.getRow(i);
//                if (row != null) {
//                    int detailQuantity = (int) row.getCell(1).getNumericCellValue();
//                    double price = row.getCell(2).getNumericCellValue();
//                    double detailTotal = row.getCell(3).getNumericCellValue();
//                    int ingredientId = (int) row.getCell(5).getNumericCellValue();
//
//                    long detailId = System.currentTimeMillis() % 1000000;
//
//                    DetailImportBillBUS detailImportBillBUS = new DetailImportBillBUS();
//                    detailImportBillBUS.addDetailImportBill(detailId, detailQuantity, price, detailTotal, billId, ingredientId);
//
//                    IngredientsBUS ingredientsBUS = new IngredientsBUS();
//                    boolean ingredientExists = ingredientsBUS.checkIngredientExistence(ingredientId);
//                    if (ingredientExists) {
//                        int existingQuantity = ingredientsBUS.getIngredientQuantity(ingredientId);
//                        int newQuantity = existingQuantity + detailQuantity;
//                        ingredientsBUS.updateIngredientQuantity(ingredientId, newQuantity);
//                    }
//                }
//            }

            workbook.close();
            loadImportBills();

            JOptionPane.showMessageDialog(null, "Dữ liệu đã được thêm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Thêm dữ liệu thất bại: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChiTiet;
    public javax.swing.JButton btnThem;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public GUI.Comp.Swing.PanelBackground panelBackground1;
    public GUI.Comp.Swing.PanelBackground panelBackground2;
    public GUI.Comp.Swing.PanelBackground panelBackground3;
    public GUI.Comp.Swing.PanelBackground panelBackground4;
    public GUI.Comp.Swing.PanelBackground panelBackground5;
    public GUI.Comp.Swing.PanelBackground panelBackground6;
    public GUI.Comp.Swing.PanelBackground panelBackground7;
    public GUI.Comp.Swing.PanelBackground panelBackground8;
    public javax.swing.JTable tbImportBill;
    // End of variables declaration//GEN-END:variables
}
